# Generated by Django 4.0.6 on 2022-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_coords", models.JSONField(default=dict)),
                ("webmap_url", models.CharField(default="", max_length=1024)),
                ("webmap_json", models.JSONField(default=dict)),
            ],
        ),
    ]
