# Generated by Django 4.0.6 on 2022-08-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="powerform_submission_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="webmap_public_url",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
