# Generated by Django 4.0.6 on 2022-08-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_map_powerform_submission_id_map_webmap_public_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="map",
            old_name="submission_coords",
            new_name="submission_attributes",
        ),
    ]
