# Generated by Django 4.0.6 on 2022-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_rename_submission_coords_map_submission_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="granted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="granted_by",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="map",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="requested_by",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="map",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "sent"), (1, "declined"), (2, "completed")], default=0
            ),
        ),
    ]
