# Generated by Django 4.0.6 on 2022-08-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_tagger", "0004_tagrequest_alter_photo_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagrequest",
            name="granted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagrequest",
            name="granted_by",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tagrequest",
            name="powerform_data_edited",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tagrequest",
            name="powerform_data_orig",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="tagrequest",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tagrequest",
            name="requested_by",
            field=models.CharField(default="", max_length=255),
        ),
    ]
