# Generated by Django 4.0.6 on 2022-08-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_tagger", "0006_tagrequest_submission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagrequest",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "sent"), (1, "declined"), (2, "completed")], default=0
            ),
        ),
    ]
